In [1]:
import csv
import pandas as pd
import numpy as np

In [2]:
file="Documents\\University_of_Miami\\Machine_Learning\\tic-tac-toe.csv"
data=pd.read_csv(file,delim_whitespace=False,header=-1)
randomData = data

In [3]:
#create training set
#0-625 are positive exmples
#626-957 are negative examples
data = np.array(data)
numPositiveExamples = np.argwhere(data[:,9]=='positive').size
numNegativeExamples = np.argwhere(data[:,9]=='negative').size
percentageTraining = .60

print(numPositiveExamples)
print(numNegativeExamples)
#add positive examples
indexForPositiveTraining = int(numPositiveExamples * percentageTraining)
positiveExamples = data[0:indexForPositiveTraining]

print(numPositiveExamples - indexForPositiveTraining)
#add negative examples
indexForNegativeTraining = numPositiveExamples + int(numNegativeExamples * percentageTraining)
negativeExamples = data[numPositiveExamples:indexForNegativeTraining]

#combine into training array
training_data = np.concatenate((positiveExamples, negativeExamples))

626
332
251


In [4]:
#create testing set
positiveTestingExamples = data[indexForPositiveTraining:numPositiveExamples]
negativeTestingExamples = data[indexForNegativeTraining:]

testing_data = np.concatenate((positiveTestingExamples, negativeTestingExamples))

In [106]:
#random data set
np.random.shuffle(data)
training_data_random = data[0:int(len(data)*.6)]
testing_data_random = data[int(len(data)*.6):len(data)]
print(training_data_random)

numPositiveExamplesRandom = np.argwhere(training_data_random[:,9]=='positive').size
numNegativeExamplesRandom = np.argwhere(training_data_random[:,9]=='negative').size

print(numPositiveExamplesRandom)
print(numNegativeExamplesRandom)

[['b' 'x' 'o' ..., 'b' 'o' 'negative']
 ['b' 'o' 'x' ..., 'x' 'b' 'positive']
 ['b' 'o' 'x' ..., 'b' 'x' 'positive']
 ..., 
 ['o' 'x' 'x' ..., 'o' 'o' 'positive']
 ['b' 'o' 'x' ..., 'o' 'b' 'negative']
 ['o' 'x' 'x' ..., 'x' 'o' 'positive']]
371
203


In [125]:
#Attribute Information:
#
#1. top-left-square: {x,o,b} 
#2. top-middle-square: {x,o,b} 
#3. top-right-square: {x,o,b} 
#4. middle-left-square: {x,o,b} 
#5. middle-middle-square: {x,o,b} 
#6. middle-right-square: {x,o,b} 
#7. bottom-left-square: {x,o,b} 
#8. bottom-middle-square: {x,o,b} 
#9. bottom-right-square: {x,o,b} 
#10. Class: {positive,negative}

numAttributes  = 9
numClasses = 2
numExamples = data.size / data[0].size
numTrain = training_data.size / training_data[0].size

indexOfPositiveTrainingExamples = np.argwhere(training_data[:,9]=='positive')
indexOfNegativeTrainingExamples = np.argwhere(training_data[:,9]=='negative')

P1 = len(indexOfPositiveTrainingExamples)/numTrain
P2 = len(indexOfNegativeTrainingExamples)/numTrain

numTrainRandom = training_data_random.size / training_data_random[0].size

indexOfPositiveTrainingExamplesRandom = np.argwhere(training_data_random[:,9]=='positive')
indexOfNegativeTrainingExamplesRandom = np.argwhere(training_data_random[:,9]=='negative')

P1random = len(indexOfPositiveTrainingExamplesRandom)/numTrainRandom
P2random = len(indexOfNegativeTrainingExamplesRandom)/numTrainRandom

print(P1random)
print(P2random)
attributeValues = ['x', 'o', 'b']
#probAttributes = [.5, .4, .1]
probAttributes = [1/3, 1/3, 1/3]

#m-estimate
m = 1

##### P(attribute 1 | class j)
probAttr1GivenC1 = np.zeros(len(attributeValues))
probAttr1GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr1GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,0]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr1GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,0]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)

##### P(attribute 2 | class j)
probAttr2GivenC1 = np.zeros(len(attributeValues))
probAttr2GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr2GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,1]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr2GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,1]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)

#### P(attribute 3 | class j)
probAttr3GivenC1 = np.zeros(len(attributeValues))
probAttr3GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr3GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,2]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr3GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,2]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)
    
##### P(attribute 4 | class j)
probAttr4GivenC1 = np.zeros(len(attributeValues))
probAttr4GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr4GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,3]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr4GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,3]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)
    
##### P(attribute 5 | class j)
probAttr5GivenC1 = np.zeros(len(attributeValues))
probAttr5GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr5GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,4]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr5GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,4]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)

##### P(attribute 6 | class j)
probAttr6GivenC1 = np.zeros(len(attributeValues))
probAttr6GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr6GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,5]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr6GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,5]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)

##### P(attribute 7 | class j)
probAttr7GivenC1 = np.zeros(len(attributeValues))
probAttr7GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr7GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,6]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr7GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,6]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)
##### P(attribute 8 | class j)
probAttr8GivenC1 = np.zeros(len(attributeValues))
probAttr8GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr8GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,7]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr8GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,7]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)
    
##### P(attribute 9 | class j)
probAttr9GivenC1 = np.zeros(len(attributeValues))
probAttr9GivenC2 = np.zeros(len(attributeValues))
for i in range(len(attributeValues)):
    probAttr9GivenC1[i] = (len(np.argwhere(training_data_random[indexOfPositiveTrainingExamplesRandom,8]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfPositiveTrainingExamples)+m)
    probAttr9GivenC2[i] = (len(np.argwhere(training_data_random[indexOfNegativeTrainingExamplesRandom,8]==attributeValues[i]))+m*probAttributes[i])/(len(indexOfNegativeTrainingExamples)+m)
    


0.6463414634146342
0.35365853658536583


In [126]:
print(probAttr1GivenC1)
print(probAttr1GivenC2)
print(probAttr2GivenC1)
print(probAttr2GivenC2)
print(probAttr3GivenC1)
print(probAttr3GivenC2)
print(probAttr4GivenC1)
print(probAttr4GivenC2)
print(probAttr5GivenC1)
print(probAttr5GivenC2)
print(probAttr6GivenC1)
print(probAttr6GivenC2)
print(probAttr7GivenC1)
print(probAttr7GivenC2)
print(probAttr8GivenC1)
print(probAttr8GivenC2)
print(probAttr9GivenC1)
print(probAttr9GivenC2)

[ 0.44237589  0.30673759  0.24024823]
[ 0.38666667  0.45666667  0.17666667]
[ 0.33067376  0.38120567  0.27748227]
[ 0.47666667  0.30666667  0.23666667]
[ 0.47960993  0.26950355  0.24024823]
[ 0.34666667  0.45166667  0.22166667]
[ 0.3785461   0.32269504  0.28812057]
[ 0.45166667  0.31666667  0.25166667]
[ 0.54875887  0.26152482  0.17907801]
[ 0.30666667  0.57666667  0.13666667]
[ 0.38120567  0.34663121  0.26152482]
[ 0.50166667  0.29666667  0.22166667]
[ 0.47163121  0.31471631  0.20301418]
[ 0.36166667  0.44166667  0.21666667]
[ 0.35992908  0.37588652  0.2535461 ]
[ 0.46666667  0.29666667  0.25666667]
[ 0.46897163  0.29609929  0.22429078]
[ 0.34166667  0.45666667  0.22166667]


In [127]:
numCorrect = 0
numIncorrect = 0
print(attributeValues)
#for i in range(len(testing_data)):
for i in range(len(testing_data_random)):
    indexForAttribute1 = -1
    indexForAttribute2 = -1 
    indexForAttribute3 = -1
    indexForAttribute4 = -1
    indexForAttribute5 = -1
    indexForAttribute6 = -1
    indexForAttribute7 = -1 
    indexForAttribute8 = -1
    indexForAttribute9 = -1 
    if attributeValues[0]==testing_data_random[i][0]:
        indexForAttribute1 = 0
    if attributeValues[1]==testing_data_random[i][0]:
        indexForAttribute1 = 1
    if attributeValues[2]==testing_data_random[i][0]:
        indexForAttribute1 = 2
    if attributeValues[0]==testing_data_random[i][1]:
        indexForAttribute2 = 0
    if attributeValues[1]==testing_data_random[i][1]:
        indexForAttribute2 = 1
    if attributeValues[2]==testing_data_random[i][1]:
        indexForAttribute2 = 2
    if attributeValues[0]==testing_data_random[i][2]:
        indexForAttribute3 = 0
    if attributeValues[1]==testing_data_random[i][2]:
        indexForAttribute3 = 1
    if attributeValues[2]==testing_data_random[i][2]:
        indexForAttribute3 = 2
    if attributeValues[0]==testing_data_random[i][3]:
        indexForAttribute4 = 0
    if attributeValues[1]==testing_data_random[i][3]:
        indexForAttribute4 = 1
    if attributeValues[2]==testing_data_random[i][3]:
        indexForAttribute4 = 2
    if attributeValues[0]==testing_data_random[i][4]:
        indexForAttribute5 = 0
    if attributeValues[1]==testing_data_random[i][4]:
        indexForAttribute5 = 1
    if attributeValues[2]==testing_data_random[i][4]:
        indexForAttribute5 = 2
    if attributeValues[0]==testing_data_random[i][5]:
        indexForAttribute6 = 0
    if attributeValues[1]==testing_data_random[i][5]:
        indexForAttribute6 = 1
    if attributeValues[2]==testing_data_random[i][5]:
        indexForAttribute6 = 2
    if attributeValues[0]==testing_data_random[i][6]:
        indexForAttribute7 = 0
    if attributeValues[1]==testing_data_random[i][6]:
        indexForAttribute7 = 1
    if attributeValues[2]==testing_data_random[i][6]:
        indexForAttribute7 = 2
    if attributeValues[0]==testing_data_random[i][7]:
        indexForAttribute8 = 0
    if attributeValues[1]==testing_data_random[i][7]:
        indexForAttribute8 = 1
    if attributeValues[2]==testing_data_random[i][7]:
        indexForAttribute8 = 2
    if attributeValues[0]==testing_data_random[i][8]:
        indexForAttribute9 = 0
    if attributeValues[1]==testing_data_random[i][8]:
        indexForAttribute9 = 1
    if attributeValues[2]==testing_data_random[i][8]:
        indexForAttribute9 = 2
    #idk why this isnt working
    #indexForAttribute1 = np.argwhere(attributeValues == testing_data[i][0])
    #indexForAttribute2 = np.where(attributeValues == testing_data[i][1])
    #indexForAttribute3 = np.where(attributeValues == testing_data[i][2])
    #indexForAttribute4 = np.where(attributeValues == testing_data[i][3])
    #indexForAttribute5 = np.where(attributeValues == testing_data[i][4])
    #indexForAttribute6 = np.where(attributeValues == testing_data[i][5])
    #indexForAttribute7 = np.where(attributeValues == testing_data[i][6])
    #indexForAttribute8 = np.where(attributeValues == testing_data[i][7])
    #indexForAttribute9 = np.where(attributeValues == testing_data[i][8])
    val1=P1*probAttr1GivenC1[indexForAttribute1]*probAttr2GivenC1[indexForAttribute2]*probAttr3GivenC1[indexForAttribute3]*probAttr4GivenC1[indexForAttribute4]*probAttr5GivenC1[indexForAttribute5]*probAttr6GivenC1[indexForAttribute6]*probAttr7GivenC1[indexForAttribute7]*probAttr8GivenC1[indexForAttribute8]*probAttr9GivenC1[indexForAttribute9]
    val2=P2*probAttr1GivenC2[indexForAttribute1]*probAttr2GivenC2[indexForAttribute2]*probAttr3GivenC2[indexForAttribute3]*probAttr4GivenC2[indexForAttribute4]*probAttr5GivenC2[indexForAttribute5]*probAttr6GivenC2[indexForAttribute6]*probAttr7GivenC2[indexForAttribute7]*probAttr8GivenC2[indexForAttribute8]*probAttr9GivenC2[indexForAttribute9]
    y = np.array([val1,val2])
    choice = np.argmax(y)
    if choice == 0 and 'positive' == testing_data_random[i][9]:
        numCorrect += 1
    elif choice == 1 and 'negative' == testing_data_random[i][9]:
        numCorrect += 1
    else:
        numIncorrect += 1

string1 = "Number of correctly classified examples in the training set is: "
string1 += str(numCorrect) 

print(string1)
string2 = "Number of incorrectly classifed examples in the training set is: " + str(numIncorrect)
print(string2)

percentageCorrect = (numCorrect / (numCorrect + numIncorrect))*100
string3 = "Percentage of correctly classified examples is: " + str(percentageCorrect)
print(string3)

['x', 'o', 'b']
Number of correctly classified examples in the training set is: 268
Number of incorrectly classifed examples in the training set is: 116
Percentage of correctly classified examples is: 69.79166666666666
